apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: time_zone
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: true
            - name: config
              mountPath: /config
              subPath: jellyfin/config
            - name: cache
              mountPath: /cache
              subPath: jellyfin/cache
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: nas-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-config

---

apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.176.220
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096