apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      # init container which creates directories for subpaths
      initContainers:
        - name: create-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/config/jellyfin/config /mnt/config/jellyfin/cache"]
          volumeMounts:
            - name: config
              mountPath: /mnt/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.6
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["IPC_LOCK"]
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-config
                  key: time_zone
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: true
            - name: config
              mountPath: /config
              subPath: jellyfin/config
            - name: config
              mountPath: /cache
              subPath: jellyfin/cache
            - name: dri
              mountPath: /dev/dri

      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: you-are-a-pirate-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: dri # stuff for quicksync to work
          hostPath:
            path: /dev/dri
            type: Directory

