apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # init container which creates directories for subpaths
      initContainers:
        - name: create-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/config/radarr/config /mnt/config/usenet/complete /mnt/config/usenet/incomplete /mnt/config/usenet/watch"]
          volumeMounts:
            - name: config
              mountPath: /mnt/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.1.1.10360-ls304 # {"$imagepolicy": "flux-system:radarr"}
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: time_zone
          volumeMounts:
            - name: media
              mountPath: /data/media
              subPath: media/
            - name: config
              mountPath: /data/usenet
              subPath: usenet/
            - name: config
              mountPath: /config
              subPath: radarr/config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: you-are-a-pirate-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config

