apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      # init container which creates directories for subpaths
      initContainers:
        - name: create-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/config/sabnzbd/config /mnt/config/usenet/complete /mnt/config/usenet/incomplete /mnt/config/usenet/watch"]
          volumeMounts:
            - name: config
              mountPath: /mnt/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:4.5.5-ls239
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: sabnzbd-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: sabnzbd-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: sabnzbd-config
                  key: time_zone
          volumeMounts:
            - name: config
              mountPath: /data/usenet
              subPath: usenet/
            - name: config
              mountPath: /config
              subPath: sabnzbd/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config

---

apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: jellyfin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.176.224
spec:
  type: LoadBalancer
  selector:
    app: sabnzbd
  ports:
    - name: http
      protocol: TCP
      port: 8989
      targetPort: 8989
