apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      # init container which creates directories for subpaths
      initContainers:
        - name: create-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/config/prowlarr/config"]
          volumeMounts:
            - name: config
              mountPath: /mnt/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.4.0.5397-ls152
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: time_zone
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: prowlarr/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config

