apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      # init container which creates directories for subpaths
      initContainers:
        - name: create-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/config/prowlarr/config"]
          volumeMounts:
            - name: config
              mountPath: /mnt/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.3.0.5236-ls133
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: user_id
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: group_id
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: prowlarr-config
                  key: time_zone
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: prowlarr/config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: you-are-a-pirate-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config

---

apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: jellyfin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.176.223
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
  ports:
    - name: http
      protocol: TCP
      port: 8989
      targetPort: 8989
