apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.176.150
    path: /mnt/CloudPool/you_are_a_pirate
  persistentVolumeReclaimPolicy: Retain # keep data on pv delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: you-are-a-pirate-pvc
  namespace: jellyfin
spec:
  volumeName: nas-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti