apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-volume
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  nfs:
    server: 192.168.176.150
    path: /mnt/apps/cluster_storage/traefik
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  volumeName: traefik-volume
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 128Mi