apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lolcathost.online-issuer
  namespace: traefik
spec:
  acme:
    email: admin@lolcathost.online
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lolcathost.online-acc-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token