apiVersion: v1
kind: ConfigMap
metadata:
    name: traefik-values
    namespace: traefik
data:
    values.yaml: |
        deployment:
            replicas: 1
        ports:
            web:
                middlewares:
                    - traefik-global-rate-limit@kubernetescrd
        ingressRoute:
            dashboard:
                enabled: true
                matchRule: Host("traefik.homelab")
                entryPoints:
                    - web
        providers:
            kubernetesGateway:
                enabled: true
        gateway:
            listeners:
                web:
                    namespacePolicy:
                        from: All
        service:
            type: LoadBalancer
            annotations:
                metallb.io/loadBalancerIPs: 192.168.176.231,fd00:1234::231
